# SPDX-FileCopyrightText: 2026 Remmina KRunner contributors
# SPDX-License-Identifier: 0BSD

function(assert_exact_line_once file expected)
    file(STRINGS "${file}" lines)
    set(count 0)
    foreach(line IN LISTS lines)
        if(line STREQUAL expected)
            math(EXPR count "${count} + 1")
        endif()
    endforeach()
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "${file}: expected exact line once: ${expected}")
    endif()
endfunction()

function(assert_key_once file key expected)
    file(STRINGS "${file}" matches REGEX "^${key}=")
    list(LENGTH matches count)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "${file}: expected key ${key} once, found ${count}")
    endif()
    list(GET matches 0 actual)
    if(NOT actual STREQUAL "${key}=${expected}")
        message(FATAL_ERROR "${file}: wrong ${key}: ${actual}")
    endif()
endfunction()

foreach(required DESKTOP_FILE SERVICE_FILE EXPECTED_EXEC EXPECTED_EXEC_VALUE)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "missing required test argument: ${required}")
    endif()
endforeach()
if(NOT EXISTS "${DESKTOP_FILE}" OR NOT EXISTS "${SERVICE_FILE}")
    message(FATAL_ERROR "configured activation metadata is missing")
endif()

assert_exact_line_once("${DESKTOP_FILE}" "[Desktop Entry]")
assert_key_once("${DESKTOP_FILE}" "Type" "Service")
assert_key_once("${DESKTOP_FILE}" "Name" "Remmina")
assert_key_once("${DESKTOP_FILE}" "Icon" "org.remmina.Remmina")
assert_key_once("${DESKTOP_FILE}" "X-KDE-PluginInfo-Name" "org.remminakrunner.KRunner")
assert_key_once("${DESKTOP_FILE}" "X-KDE-PluginInfo-Version" "0.1.0")
assert_key_once("${DESKTOP_FILE}" "X-KDE-PluginInfo-License" "0BSD")
assert_key_once("${DESKTOP_FILE}" "X-Plasma-API" "DBus2")
assert_key_once("${DESKTOP_FILE}" "X-Plasma-DBusRunner-Service" "org.remminakrunner.KRunner")
assert_key_once("${DESKTOP_FILE}" "X-Plasma-DBusRunner-Path" "/runner")
assert_key_once("${DESKTOP_FILE}" "X-Plasma-Runner-Match-Regex" "(?i)^rem(?:\\s.*)?$")
assert_key_once("${DESKTOP_FILE}" "X-Plasma-Runner-Syntaxes" "rem :q:;rem new")
assert_key_once("${DESKTOP_FILE}" "X-Plasma-Runner-Unique-Results" "true")
assert_key_once("${DESKTOP_FILE}" "X-KDE-ConfigModule" "kf6/krunner/kcms/kcm_remmina_krunner")

assert_exact_line_once("${SERVICE_FILE}" "[D-BUS Service]")
assert_key_once("${SERVICE_FILE}" "Name" "org.remminakrunner.KRunner")
assert_key_once("${SERVICE_FILE}" "Exec" "${EXPECTED_EXEC_VALUE}")
file(STRINGS "${SERVICE_FILE}" exec_lines REGEX "^Exec=")
list(LENGTH exec_lines exec_count)
if(NOT exec_count EQUAL 1)
    message(FATAL_ERROR "activation metadata must contain exactly one Exec line")
endif()
list(GET exec_lines 0 exec_line)
if(NOT exec_line MATCHES "^Exec=\"(.*)\"$")
    message(FATAL_ERROR "activation Exec must be one quoted argument: ${exec_line}")
endif()
set(decoded "${CMAKE_MATCH_1}")
string(REPLACE "\\\\" "\\" decoded "${decoded}")
string(REPLACE "\\\"" "\"" decoded "${decoded}")
string(REPLACE "\\\\" "\\" decoded "${decoded}")
if(NOT IS_ABSOLUTE "${decoded}" OR NOT decoded STREQUAL EXPECTED_EXEC)
    message(FATAL_ERROR "activation Exec did not decode to the installed executable")
endif()
